### ISSUE TITLE
Pytorch-lightning ValueError: bad value(s) in fds_to_keep and DistributedDataParallel

### ISSUE THREAD

**Issue by Demirrr** [dice-group/DAIKIRI-Embedding#10]
If we run main program with the following input configuration
```
Namespace(accelerator=None, accumulate_grad_batches=None, add_reciprical=False, amp_backend='native',
                  amp_level=None, apply_unit_norm=False, auto_lr_find=False, auto_scale_batch_size=False,
                  auto_select_gpus=False, batch_size=2048, benchmark=False, check_val_every_n_epoch=10,
                  checkpoint_callback=False, continue_training=1, default_root_dir=None, deserialize_flag=None,
                  detect_anomaly=False, deterministic=False, devices=None, embedding_dim=10, enable_checkpointing=True,
                  enable_model_summary=True, enable_progress_bar=True, eval=False, fast_dev_run=False,
                  feature_map_dropout_rate=0.3, find_unused_parameters=False, flush_logs_every_n_steps=None, gpus=None,
                  gradient_clip_algorithm=None, gradient_clip_val=None, hidden_dropout_rate=0.1, input_dropout_rate=0.1,
                  ipus=None, kernel_size=3, kvsall=False, large_kg_parse=False, learning_rate=0.01,
                  limit_predict_batches=1.0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0,
                  log_every_n_steps=50, log_gpu_memory=None, logger=False, max_epochs=50, max_steps=-1, max_time=None,
                  min_epochs=None, min_steps=None, model='QMult', move_metrics_to_cpu=False,
                  multiple_trainloader_mode='max_size_cycle', negative_sample_ratio=1, num_entities=135,
                  num_folds_for_cv=0, num_nodes=1, num_of_output_channels=8, num_processes=4, num_relations=46,
                  num_sanity_val_steps=2, num_workers=4, overfit_batches=0.0, path_dataset_folder='KGs/UMLS',
                  plugins=None, precision=32, prepare_data_per_node=None, process_position=0, profiler=None,
                  progress_bar_refresh_rate=None, read_only_few=0, reload_dataloaders_every_epoch=False,
                  reload_dataloaders_every_n_epochs=0, replace_sampler_ddp=True, resume_from_checkpoint=None,
                  scoring_technique='NegSample', shallom_width_ratio_of_emb=1.5, stochastic_weight_avg=False,
                  storage_path='DAIKIRI_Storage', strategy=None, sync_batchnorm=False, terminate_on_nan=None,
                  tpu_cores=None, track_grad_norm=-1, val_check_interval=1.0, weights_save_path=None,
                  weights_summary='top')
```

We get the following error
```
Traceback (most recent call last):
  File "/home/demir/Desktop/Softwares/DAIKIRI_Emb/main.py", line 60, in <module>
    exc.start()
  File "/home/demir/Desktop/Softwares/DAIKIRI_Emb/executer.py", line 129, in start
    trained_model = self.train_and_eval()
  File "/home/demir/Desktop/Softwares/DAIKIRI_Emb/executer.py", line 198, in train_and_eval
    trained_model = self.training_negative_sampling()
  File "/home/demir/Desktop/Softwares/DAIKIRI_Emb/executer.py", line 276, in training_negative_sampling
    self.trainer.fit(model, train_dataloaders=dataset.train_dataloader())
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 173, in start_training
    self.spawn(self.new_process, trainer, self.mp_queue, return_result=False)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 201, in spawn
    mp.spawn(self._wrapped_function, args=(function, args, kwargs, return_queue), nprocs=self.num_processes)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/demir/anaconda3/envs/daikiri/lib/python3.7/multiprocessing/util.py", line 455, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep
```

1. There are few opened issues in pytorch lgihtning (PL) related to this error. **If you reduce the num_workers=1, all works seamlesly.** However, this is not what we want :)

2. The above written error is caused by DistributedDataParallel DDP.  As long as you request multi-CPUs, it appears to me that PL autimatically uses DDP Spawn as indirectly noted [here](https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#distributed-modes) and explicitly shown in the above message (**packages/pytorch_lightning/plugins/training_type/ddp_spawn.py**

3. f you use Data Parallel (strategy='dp') (multiple-gpus, 1 machine), then you receive the following warning although we do not use DDP constructor.

_Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters._

4. (3) is kinda frustrating as in our configuration, we do not use DDP. However, we may have already found an hard coded workaround, namely,
using `plugins=DataParallelPlugin()

Hence, it seems to me that, currently we are considering each CPU as a node, hence each printout appears # of CPU times

**Comment by Demirrr** [comment]
Current solution =>
```python
if self.args.gpus:
    self.trainer = pl.Trainer.from_argparse_args(self.args, plugins=[DDPPlugin(find_unused_parameters=False)])
else:
    self.trainer = pl.Trainer.from_argparse_args(self.args)
```
